version: "3.7"

services:
  node-red:
    # image: nodered/node-red:latest
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - TZ=Europe/Madrid
    ports:
      - "1880:1880"
    volumes:
      - ./data/:/data
    # command: 
    #   - cd /data && npm install
